name: CD

on:
  push:
    branches:
      - 'main'
      - 'feature/rangjin/cd'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Make yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.SERVER_APPLICATION_YML }}" | base64 --decode > ./src/main/resources/application.yml
        shell: bash

      - name: Web Docker Build and Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} -f Dockerfile . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Executing Remote ssh Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            chmod 777 /home/ubuntu/docker/deploy.sh
            /home/ubuntu/docker/deploy.sh $DOCKER_USERNAME
